// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI466yx0HVDfjS2Cb6EDIYiKi2pKbV95w',
    appId: '1:140871474960:web:74e3dc9ea8d89382320f95',
    messagingSenderId: '140871474960',
    projectId: 'budget-app-562e7',
    authDomain: 'budget-app-562e7.firebaseapp.com',
    storageBucket: 'budget-app-562e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCstpHNLLNDZ4e1IIGJ5MEiHzoXFF7t5Gc',
    appId: '1:140871474960:android:348454ceac8f0483320f95',
    messagingSenderId: '140871474960',
    projectId: 'budget-app-562e7',
    storageBucket: 'budget-app-562e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArHTLF-aZye_Qh8ZVR5RFWVpf3rVHis2g',
    appId: '1:140871474960:ios:60f92d0a308988ef320f95',
    messagingSenderId: '140871474960',
    projectId: 'budget-app-562e7',
    storageBucket: 'budget-app-562e7.appspot.com',
    iosBundleId: 'com.example.budgetApp',
  );
}
